apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-viewer-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: myscript
  namespace: default
roleRef:
  kind: Role
  name: deployment-viewer
  apiGroup: rbac.authorization.k8s.io
