apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-rb
  namespace: default
subjects:
- kind: User
  name: tom
  namespace: default
roleRef:
  kind: Role
  name: dev-cr
  apiGroup: rbac.authorization.k8s.io
