apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels: 
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.20
        ports:
        - containerPort: 80
        command: ['sh', '-c']
        args:
        - |
          while true; do
            echo "$(date) INFO some app data" >> /var/log/myapp.log;
            sleep 5;
          done
        
        volumeMounts:
        - name: log-data
          mountPath: /var/log

      - name: log-sidecar
        image: busybox:1.28
        command: ['sh', '-c']
        args:
        - tail -f /var/sidecar/myapp.log

        volumeMounts: 
          - name: log-data
            mountPath: "/var/sidecar"

      volumes:
      - name: log-data
        emptyDir: {}
