apiVersion: v1
kind: Pod
metadata:
  name: pod-with-tolerants
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - effect: NoSchedule
    operator: Exists
  nodeName: master-learning
