apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec: #it indicate storage backend, QAWS, Google, local, etc 
  hostPath:
    path: "/mnt/data"
  capacity:
    storage: 4Gi
  accessModes:
  - ReadWriteMany
